volumes:
  ollama_data: {}

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    tty: true
    restart: unless-stopped
    # Uncomment the following lines to enable GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scrapelm
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    tty: true
    working_dir: /app
    command: ["tail", "-f", "/dev/null"]
